### ISSUE TITLE
`"userSetServerless" is null` error when upgrading to version `2.1.0.22` 

### ISSUE THREAD

**Issue by NathanEckert** [aws/amazon-redshift-jdbc-driver#103]
## Driver version

Upgrade from driver `2.1.0.19` to `2.1.0.22`

## Redshift version

```
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.57864
```

Other dependency: `com.zaxxer:HikariCP` version `5.0.1`

## Client Operating System

```
Linux Ubuntu 22.04.3 LTS (Jammy Jellyfish)
```

## JAVA/JVM version

```
mvn --version
Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546)
Maven home: /home/nec/.sdkman/candidates/maven/current
Java version: 17.0.9, vendor: Eclipse Adoptium, runtime: /home/nec/.sdkman/candidates/java/17.0.9-tem
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.2.0-36-generic", arch: "amd64", family: "unix"
```

## Problem description

Recently, I had a performance issue with `com.amazon.redshift:redshift-jdbc42`, when upgrading from version `2.1.0.19` to `2.1.0.20`.
It was tracked by https://github.com/aws/amazon-redshift-jdbc-driver/issues/100.

When using the newly fixed version (so bumping from `2.1.0.19` to `2.1.0.22`), one single test of our test suite failed.

## JDBC trace logs

```
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Something unusual has occurred to cause the driver to fail. Please report this exception:Cannot invoke "String.equalsIgnoreCase(String)" because "userSetServerless" is null

	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at com.activeviam.database.redshift.internal.config.TestBugHikari.testBugHikariWithNewJdbcDriver(TestBugHikari.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:129)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:129)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: com.amazon.redshift.util.RedshiftException: Something unusual has occurred to cause the driver to fail. Please report this exception:Cannot invoke "String.equalsIgnoreCase(String)" because "userSetServerless" is null
	at com.amazon.redshift.Driver.connect(Driver.java:339)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	... 61 more
Caused by: java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "userSetServerless" is null
	at com.amazon.redshift.core.IamHelper.setIAMProperties(IamHelper.java:126)
	at com.amazon.redshift.jdbc.RedshiftConnectionImpl.<init>(RedshiftConnectionImpl.java:286)
	at com.amazon.redshift.Driver.makeConnection(Driver.java:481)
	at com.amazon.redshift.Driver.connect(Driver.java:302)
	... 66 more
```

## Reproduction code

```java
package com.activeviam.database.redshift.internal.config;

import static com.activeviam.directquery.test.internal.redshift.RedshiftTestConstants.CLUSTER_URL;

import com.activeviam.directquery.test.internal.redshift.RedshiftTestConstants;
import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import lombok.Cleanup;
import org.junit.jupiter.api.Test;

public class TestBugHikari {

	private static final String connectionString =
			"jdbc:redshift:iam://" + CLUSTER_URL + RedshiftTestConstants.TEST_DATABASE_NAME;

	@Test
	void testBugHikariWithNewJdbcDriver() {
		HikariConfig config = new HikariConfig();
		config.setJdbcUrl(connectionString);
		@Cleanup
		var dataSource = new HikariDataSource(config);
	}

}

```

**Comment by bhvkshah** [comment]
@NathanEckert this should be fixed in this commit: https://github.com/aws/amazon-redshift-jdbc-driver/commit/0ab3daca04861a40f00d2c3b3f4439c1fbf61a47

Can you please check?

**Comment by joatcoursera** [comment]
Hi @bhvkshah , I am also encountering this issue. I think the commit you linked would fix this issue, but this change doesn't seem to be included in the published `2.1.0.22` version for some reason:

![image](https://github.com/aws/amazon-redshift-jdbc-driver/assets/100233455/3e2c919f-78d4-4dfa-9ef4-1f911cbcd6d3)

**Comment by bhvkshah** [comment]
@joatcoursera Under the releases section it does seem to include the commit linked above as part of the 2.1.0.22 release. Can you try pulling again?

**Comment by joatcoursera** [comment]
I tried but no luck :(
Actually if you download the source directly from Maven, you can see it doesn't include the commit: https://repo1.maven.org/maven2/com/amazon/redshift/redshift-jdbc42/2.1.0.22/

**Comment by bhvkshah** [comment]
@joatcoursera We have another release for version 2.1.0.23 planned for early next week. Until then can you try the workaround of setting isserverless=false as part of the connection options?

**Comment by NathanEckert** [comment]
> @NathanEckert this should be fixed in this commit: [0ab3dac](https://github.com/aws/amazon-redshift-jdbc-driver/commit/0ab3daca04861a40f00d2c3b3f4439c1fbf61a47)
> 
> Can you please check?

I'll try as soon as 2.1.0.23 is out

**Comment by bhvkshah** [comment]
Hey @NathanEckert @joatcoursera driver version 2.1.0.23 is out

**Comment by NathanEckert** [comment]
Thanks, it does fix indeed the issue
