### ISSUE TITLE
Getting java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:363) exception intermittently

### ISSUE THREAD

**Issue by shraddha-ca** [aws/amazon-redshift-jdbc-driver#104]
## Driver version

2.1.0.18

## Redshift version

PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.59591

## Client Operating System

linux/amd64

## Problem description

We use a [Kafka Connect Docker Image](https://hub.docker.com/layers/confluentinc/cp-kafka-connect/7.4.1/images/sha256-b2e3a877fe6e6aac12abed3333176b939282135b95640b8d30798fa5e38e2974?context=explore) deployed over ECS with a [JDBC sink connector](https://github.com/confluentinc/kafka-connect-jdbc/tree/v10.6.0) `v10.6.0` and the Redshift JDBC driver to transfer data from MSK into a Redshift Serverless instance. 
This intermittently fails with the following stack trace:
```
Caused by: java.util.NoSuchElementException
	at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:363)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResultsOnThread(QueryExecutorImpl.java:2368)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1881)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1873)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:595)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.internalExecuteBatch(RedshiftStatementImpl.java:988)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeBatch(RedshiftStatementImpl.java:1016)
	at com.amazon.redshift.jdbc.RedshiftPreparedStatement.executeBatch(RedshiftPreparedStatement.java:1765)
	at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:196)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:186)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:80)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:84)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:336)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
when an `INSERT` query has run after a long time. Redshift Serverless logs suggest that the query succeeds and then the connector fails. 
Usually restarting the task fixes the issue but sometimes it fails with another error:
```
Caused by: java.lang.IllegalStateException: Received resultset tuples, but no field structure for them
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResultsOnThread(QueryExecutorImpl.java:2127)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1881)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1873)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:370)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeInternal(RedshiftStatementImpl.java:515)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.execute(RedshiftStatementImpl.java:436)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeWithFlags(RedshiftStatementImpl.java:377)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeCachedSql(RedshiftStatementImpl.java:363)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeWithFlags(RedshiftStatementImpl.java:340)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeQuery(RedshiftStatementImpl.java:268)
	at com.amazon.redshift.jdbc.RedshiftDatabaseMetaData.getExtSchemaPatternMatch(RedshiftDatabaseMetaData.java:5301)
	at com.amazon.redshift.jdbc.RedshiftDatabaseMetaData.getTables(RedshiftDatabaseMetaData.java:1577)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.tableExists(GenericDatabaseDialect.java:587)
	at io.confluent.connect.jdbc.util.TableDefinitions.get(TableDefinitions.java:61)
	at io.confluent.connect.jdbc.sink.DbStructure.createOrAmendIfNecessary(DbStructure.java:64)
	at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:122)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:74)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:84)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:336)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

## Reproduction code
The following configurations are set on the connector, all other values are left as default:
```
connection.url: jdbc:redshift://host:port/dbname
connection.user: username
connection.password: password
table.name.format: tablename
```
The connection parameters are fetched [here](https://github.com/confluentinc/kafka-connect-jdbc/blob/aa8466c30b09d3d12f4ca502b16f3c19ac7b2593/src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java#L66) and passed on to the driver [here](https://github.com/confluentinc/kafka-connect-jdbc/blob/aa8466c30b09d3d12f4ca502b16f3c19ac7b2593/src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java#L245)

**Comment by shawnazhaoxy** [comment]
Hi 
> bhvkshah , any update?

**Comment by shawnazhaoxy** [comment]
Hi, @bhvkshah any update on the issue?

**Comment by bhvkshah** [comment]
Hi @shawnazhaoxy @shraddha-ca , thanks for following up. I believe this could be an issue in the server. Are you able to provide DEBUG level driver logs, as well as a wireshark trace during a repro which I could then pass on to the internal server team?

**Comment by bhvkshah** [comment]
@shraddha-ca can updates on providing more info on this?

**Comment by shraddha-ca** [comment]
@bhvkshah apologies for the delay. We didn't have an easy way to get Debug Logs, however, I have attached the logs from the latest failure for: 
```
Caused by: java.util.NoSuchElementException
	at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:363)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResultsOnThread(QueryExecutorImpl.java:2368)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1881)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1873)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:595)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.internalExecuteBatch(RedshiftStatementImpl.java:988)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeBatch(RedshiftStatementImpl.java:1016)
	at com.amazon.redshift.jdbc.RedshiftPreparedStatement.executeBatch(RedshiftPreparedStatement.java:1765)
	at io.confluent.connect.jdbc.sink.BufferedRecords.executeUpdates(BufferedRecords.java:196)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:186)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:80)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:84)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:336)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
[extract-2024-06-05T13_32_04.239Z.csv](https://github.com/user-attachments/files/15588270/extract-2024-06-05T13_32_04.239Z.csv)

**Comment by shraddha-ca** [comment]
My suspicion is that the portal is already closed, mostly from looking at these lines:

|Date                    |Host|Service                                                                                             |Message                                      |
|------------------------|----|----------------------------------------------------------------------------------------------------|---------------------------------------------|
|2024-06-05T12:03:13.711Z|"kafka-ops"|"cloudwatch"                                                                                        |Jun 05 12:03:13.711 DEBUG [57817 task-thread] com.amazon.redshift.core.v3.QueryExecutorImpl.receiveRFQ: <=BE ReadyForQuery(I)|
|2024-06-05T12:03:13.711Z|"kafka-ops"|"cloudwatch"                                                                                        |Jun 05 12:03:13.711 DEBUG [57817 task-thread] com.amazon.redshift.core.v3.QueryExecutorImpl.processSyncOnClose: <=BE CloseComplete|
|2024-06-05T12:03:13.711Z|"kafka-ops"|"cloudwatch"                                                                                        |Jun 05 12:03:13.711 DEBUG [57817 task-thread] com.amazon.redshift.core.v3.QueryExecutorImpl.processSyncOnClose: <=BE CloseComplete|
|2024-06-05T12:03:13.709Z|"kafka-ops"|"cloudwatch"                                                                                        |Jun 05 12:03:13.709 DEBUG [57817 task-thread] com.amazon.redshift.core.v3.QueryExecutorImpl.sendSync: FE=> Sync|
|2024-06-05T12:03:13.709Z|"kafka-ops"|"cloudwatch"                                                                                        |Jun 05 12:03:13.709 DEBUG [57817 task-thread] com.amazon.redshift.core.v3.QueryExecutorImpl.sendFlush: FE=> Flush|
|2024-06-05T12:03:13.709Z|"kafka-ops"|"cloudwatch"                                                                                        |Jun 05 12:03:13.709 DEBUG [57817 task-thread] com.amazon.redshift.core.v3.QueryExecutorImpl.sendClosePortal: FE=> ClosePortal(C_10-1848892317217922)|
|2024-06-05T12:03:13.709Z|"kafka-ops"|"cloudwatch"                                                                                        |Jun 05 12:03:13.709 DEBUG [57817 task-thread] com.amazon.redshift.core.v3.QueryExecutorImpl.sendCloseStatement: FE=> CloseStatement(S_9-1848892317145757)|
|2024-06-05T12:03:13.709Z|"kafka-ops"|"cloudwatch"                                                                                        |Jun 05 12:03:13.709 FUNCTION [57817 task-thread] com.amazon.redshift.jdbc.RedshiftStatementImpl.cancel: Return|
|2024-06-05T12:03:13.709Z|"kafka-ops"|"cloudwatch"                                                                                        |Jun 05 12:03:13.709 ERROR [57817 task-thread] com.amazon.redshift.jdbc.RedshiftStatementImpl.cancel: statementState is StatementCancelState.IDLE|
|2024-06-05T12:03:13.709Z|"kafka-ops"|"cloudwatch"                                                                                        |Jun 05 12:03:13.709 FUNCTION [57817 task-thread] com.amazon.redshift.jdbc.RedshiftStatementImpl.cancel: Enter (value)|
|2024-06-05T12:03:13.709Z|"kafka-ops"|"cloudwatch"                                                                                        |Jun 05 12:03:13.709 FUNCTION [57817 task-thread] com.amazon.redshift.jdbc.RedshiftStatementImpl.close: Enter (value)|
|2024-06-05T12:03:13.709Z|"kafka-ops"|"cloudwatch"                                                                                        |Jun 05 12:03:13.709 FUNCTION [57817 task-thread] com.amazon.redshift.jdbc.RedshiftPreparedStatement.executeUpdate: Return 0|
|2024-06-05T12:03:13.708Z|"kafka-ops"|"cloudwatch"                                                                                        |Jun 05 12:03:13.708 DEBUG [57817 task-thread] com.amazon.redshift.core.v3.QueryExecutorImpl.processResultsOnThread: ReadyForQuery will exit from processResultsOnThread loop|
|2024-06-05T12:03:13.708Z|"kafka-ops"|"cloudwatch"                                                                                        |Jun 05 12:03:13.708 DEBUG [57817 task-thread] com.amazon.redshift.core.v3.QueryExecutorImpl.receiveRFQ: <=BE ReadyForQuery(I)|
|2024-06-05T12:03:13.708Z|"kafka-ops"|"cloudwatch"                                                                                        |Jun 05 12:03:13.708 DEBUG [57817 task-thread] com.amazon.redshift.core.v3.QueryExecutorImpl.processResultsOnThread: FE=> Received packet of type:90=Z|

**Comment by shraddha-ca** [comment]
@bhvkshah Is there any update on this? Even throwing a `java.sql.SQLException` will suffice for our use case. This will trigger an automatic restart for us.

**Comment by bhvkshah** [comment]
Hey @shraddha-ca , I no longer work on this project. Pinging @bsharifi who does.

**Comment by paoliniluis** [comment]
Hi there, we're hitting this issue in Metabase as well @bsharifi
