### ISSUE TITLE
Unable to use an SSO IAM profile to generate temporary credentials - No AWS profile named `my_sso_profile`

### ISSUE THREAD

**Issue by karlanka** [aws/amazon-redshift-jdbc-driver#35]
## Driver version
`RedshiftJDBC42-no-awssdk-1.2.55.1083`

## Redshift version
`PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.31651`

## Client Operating System
Os: Windows 10 Pro 
Version: 20H2
Build: 19042.1237

## Table schema
N/A

## Problem description
We have configured a permission set, that allows calling get-cluster-credentials, in AWS SSO and assigned this to users in same account as Redshift. 

I am able to use the CLI to generate credentials like this:
`$ aws redshift get-cluster-credentials --cluster-identifier redshift-cluster-1 --db-user karlanka --auto-create --db-name dev --region eu-west-1 --profile my_sso_profile`

Which returns credentials that I can log in with.

The `my_sso_profile profile` looks like this:
```
[profile my_sso_profile]
sso_start_url = <redacted> 
sso_region = eu-west-1
sso_account_id = <redacted>
sso_role_name = redshift_sso_role
region = eu-west-1
output = json
```
I have configured my jdbc-driver as such:
jdbc:redshift:iam://{host}:{port}/{database}

And I supply host, port and database in my SQL client.

In driver properties I have set 
```
AutoCreate=true
Profile=my_sso_profile
region=eu-west-1
DbUser=karlanka
```

**When trying to log I get: No AWS profile named `my_sso_profile`**

If I instead use a non-sso profile (a profile with keys in `~/.aws/credentials`) I can log in with the same setup.

My guess is that the driver is simply not supporting SSO-profiles? I have basically no knowledge of Java, but I could not find any reference to [`getRoleCredentials`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/sso/AWSSSOClient.html#getRoleCredentials-com.amazonaws.services.sso.model.GetRoleCredentialsRequest-) in the repository (which I assume is needed to get keys for an sso profile/role). 

## JDBC trace logs
```
Oct 12 08:27:38.047 INFO  20 com.amazon.redshift.core.PGJDBCConnection.connect: unknownLength is null, falls back to default value: 2147483647
Oct 12 08:27:38.064 DEBUG 20 com.amazon.redshift.core.IamHelper.IamHelper: PGJDBCSettings{m_host='<redacted>', m_port=5439, m_loginTimeoutMS=0, m_rowsFetchedPerBlock=10000, m_unknownLength=2147483647, m_authMech=VERIFY_CA, m_username='null', m_password='null', m_krbRealm='null', m_krbServiceName='null', m_krbHostFQDN='null', m_sslKeyStore='null', m_sslKeyStorePwd='null', m_sslPassword='null', m_sslKey='null', m_sslCert='null', m_sslRootCert='null', m_Schema='dev', m_delegationUID='null', m_nRowMode=0, m_newTCPConnectionKeepAliveMinutes=5, m_filterLevel='NOTICE', m_socketTimeoutMS=0, m_disableIsValid=false, m_iamAuth=true, m_iamAccessKeyID='null', m_iamSecretKey='null', m_iamSessionToken='null', m_profile='null', m_externalId='null', m_clusterIdentifier='null', m_iamDuration=0, m_autocreate=null, m_dbUser='null', m_dbGroups=null, m_forceLowercase=null, m_endpoint='null', m_awsRegion='null', m_credentialsProvider='null', m_sslTrustStorePath='null', m_sslTrustStorePwd='null', m_pluginArgs={}, m_hasExtSchemaPatternMatch=false, m_selectorProvider='null', m_selectorProviderArg='null', m_readonly=false', m_queryGroup=null', m_databaseMetadataCurrentDbOnly=true}
Oct 12 08:27:38.064 DEBUG 20 com.amazon.redshift.core.IamHelper.setIAMProperties: {AutoCreate=Variant[type: TYPE_WSTRING, value: true], ClusterID=Variant[type: TYPE_WSTRING, value: redshift-cluster-1], ConnSchema=Variant[type: TYPE_WSTRING, value: dev], DbUser=Variant[type: TYPE_WSTRING, value: karlanka], Host=Variant[type: TYPE_WSTRING, value: <redacted>], IAMAuth=Variant[type: TYPE_WSTRING, value: true], LogLevel=Variant[type: TYPE_WSTRING, value: 5], LogPath=Variant[type: TYPE_WSTRING, value: c:/temp], Port=Variant[type: TYPE_WSTRING, value: 5439], prepareThreshold=Variant[type: TYPE_WSTRING, value: 0], profile=Variant[type: TYPE_WSTRING, value: <redacted>], PWD=Variant[type: TYPE_WSTRING, value: ****], ssl=Variant[type: TYPE_WSTRING, value: true], sslpasswordcallback=Variant[type: TYPE_WSTRING, value: org.jkiss.dbeaver.runtime.net.DefaultCallbackHandler], UID=Variant[type: TYPE_WSTRING, value: karlanka]}
Oct 12 08:27:38.064 ERROR 20 com.amazon.exceptions.ExceptionConverter.toSQLException: [JDBC Driver]No AWS profile named 'my_sso_profile'
java.sql.SQLException: [JDBC Driver]No AWS profile named 'redshift_playground'
	at com.amazon.redshift.core.PluginProfilesConfigFile.getCredentials(Unknown Source)
	at com.amazon.redshift.core.PluginProfilesConfigFile.getCredentials(Unknown Source)
	at com.amazonaws.auth.profile.ProfileCredentialsProvider.getCredentials(ProfileCredentialsProvider.java:161)
	at com.amazon.redshift.core.IamHelper.setIAMCredentials(Unknown Source)
	at com.amazon.redshift.core.IamHelper.setIAMProperties(Unknown Source)
	at com.amazon.redshift.core.PGJDBCConnection.connect(Unknown Source)
	at com.amazon.jdbc.common.BaseConnectionFactory.doConnect(Unknown Source)
	at com.amazon.jdbc.common.AbstractDriver.connect(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:176)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:195)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:457)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.checkInstanceConnection(PostgreDatabase.java:222)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.<init>(PostgreDatabase.java:115)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.createDatabaseImpl(PostgreDataSource.java:240)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:146)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:89)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:97)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:108)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:918)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.amazonaws.SdkClientException: No AWS profile named 'my_sso_profile'
	... 26 more
```
```
Oct 12 08:27:38.031 INFO  20 com.amazon.jdbc.common.BaseConnectionFactory.getConnection: SDK Version: 10.1.20.1161
Oct 12 08:27:38.031 INFO  20 com.amazon.jdbc.common.BaseConnectionFactory.getConnection: Driver Version: 01.02.55.1083
Oct 12 08:27:38.031 INFO  20 com.amazon.jdbc.common.BaseConnectionFactory.getConnection: JVM Name: OpenJDK 64-Bit Client VM
Oct 12 08:27:38.031 INFO  20 com.amazon.jdbc.common.BaseConnectionFactory.getConnection: JVM Specification Version: 11
Oct 12 08:27:38.031 INFO  20 com.amazon.jdbc.common.BaseConnectionFactory.getConnection: JVM Implementation Version: 11.0.11+9
Oct 12 08:27:38.031 INFO  20 com.amazon.jdbc.common.BaseConnectionFactory.getConnection: JVM Vendor: Oracle Corporation
Oct 12 08:27:38.031 INFO  20 com.amazon.jdbc.common.BaseConnectionFactory.getConnection: Operating System Name: Windows 10
Oct 12 08:27:38.031 INFO  20 com.amazon.jdbc.common.BaseConnectionFactory.getConnection: Operating System Version: 10.0
Oct 12 08:27:38.031 INFO  20 com.amazon.jdbc.common.BaseConnectionFactory.getConnection: Operating System Architecture: amd64
Oct 12 08:27:38.031 INFO  20 com.amazon.jdbc.common.BaseConnectionFactory.getConnection: Locale Name: en
Oct 12 08:27:38.031 INFO  20 com.amazon.jdbc.common.BaseConnectionFactory.getConnection: Default Charset Encoding: windows-1252
```

**Comment by karlanka** [comment]
Oh, I see. Sure, will report after trying 2.x in a new ticket.
