### ISSUE TITLE
Unable to use an SSO IAM profile to generate temporary credentials - No AWS profile named my_sso_profile

### ISSUE THREAD

**Issue by karlanka** [aws/amazon-redshift-jdbc-driver#36]
## Driver version
`redshift-jdbc42-2.1.0.1`

## Redshift version
`PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.31651`

## Client Operating System
Os: Windows 10 Pro 
Version: 20H2
Build: 19042.1237

## Problem description
We have configured a permission set, that allows calling get-cluster-credentials, in AWS SSO and assigned this to users in same account as Redshift. 

I am able to use the CLI to generate credentials like this:
`$ aws redshift get-cluster-credentials --cluster-identifier redshift-cluster-1 --db-user karlanka --auto-create --db-name dev --region eu-west-1 --profile my_sso_profile`

Which returns credentials that I can log in with.

The `my_sso_profile profile` looks like this:
```
[profile my_sso_profile]
sso_start_url = <redacted> 
sso_region = eu-west-1
sso_account_id = <redacted>
sso_role_name = redshift_sso_role
region = eu-west-1
output = json
```
I have configured my jdbc-driver as such:
jdbc:redshift:iam://{host}:{port}/{database}

And I supply host, port and database in my SQL client.

In driver properties I have set 
```
AutoCreate=true
Profile=my_sso_profile
Region=eu-west-1
DbUser=karlanka
ClusterID=redshift-cluster-1
```

When trying to log I get: 
```
Something unusual has occured to cause the driver to fail. Please report this exception.
No AWS Profile named my_sso_profile
```

If I instead use a non-sso profile (a profile with keys in `~/.aws/credentials`) I can log in with the same setup.

My guess is that the driver is simply not supporting SSO-profiles? I have basically no knowledge of Java, but I could not find any reference to [`getRoleCredentials`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/sso/AWSSSOClient.html#getRoleCredentials-com.amazonaws.services.sso.model.GetRoleCredentialsRequest-) in the repository (which I assume is needed to get keys for an sso profile/role). 

## JDBC trace logs
```
Oct 14 08:34:25.779 DEBUG  [59 Connect to '2.1.1 IAM'] com.amazon.redshift.Driver.connect: ===================================
Oct 14 08:34:25.779 FUNCTION  [59 Connect to '2.1.1 IAM'] com.amazon.redshift.Driver.connect:  Enter (jdbc:redshift:iam://<redshift-host>:5439/dev,{ClusterID=redshift-cluster-1, ssl=true, Profile=my_sso_profile, LogLevel=5, password=***, DbUser=karlanka, prepareThreshold=0, AutoCreate=true, Region=eu-west-1, sslpasswordcallback=org.jkiss.dbeaver.runtime.net.DefaultCallbackHandler, LogPath=c:/temp/211, user=redshift_master}) 
Oct 14 08:34:25.779 DEBUG  [59 Connect to '2.1.1 IAM'] com.amazon.redshift.Driver.connect: Connecting with URL: jdbc:redshift:iam://<redshift-host>:5439/dev
Oct 14 08:34:25.779 DEBUG  [59 Connect to '2.1.1 IAM'] com.amazon.redshift.jdbc.RedshiftConnectionImpl.RedshiftConnectionImpl: Redshift JDBC Driver 2.1.0.1
Oct 14 08:34:25.779 DEBUG  [59 Connect to '2.1.1 IAM'] com.amazon.redshift.jdbc.RedshiftConnectionImpl.RedshiftConnectionImpl: Start IAM authentication
Oct 14 08:34:25.780 DEBUG  [59 Connect to '2.1.1 IAM'] com.amazon.redshift.core.IamHelper.setIAMCredentials: IDP Credential Provider com.amazonaws.auth.profile.ProfileCredentialsProvider@6b1541d5:null
Oct 14 08:34:25.780 DEBUG  [59 Connect to '2.1.1 IAM'] com.amazon.redshift.core.IamHelper.setIAMCredentials: Calling provider.getCredentials()
Oct 14 08:34:25.780 ERROR  [59 Connect to '2.1.1 IAM'] com.amazon.redshift.Driver.connect: com.amazonaws.SdkClientException: No AWS profile named 'my_sso_profile'
	at com.amazon.redshift.core.PluginProfilesConfigFile.getCredentials(PluginProfilesConfigFile.java:76)
	at com.amazon.redshift.core.PluginProfilesConfigFile.getCredentials(PluginProfilesConfigFile.java:30)
	at com.amazonaws.auth.profile.ProfileCredentialsProvider.getCredentials(ProfileCredentialsProvider.java:161)
	at com.amazon.redshift.core.IamHelper.setIAMCredentials(IamHelper.java:536)
	at com.amazon.redshift.core.IamHelper.setIAMProperties(IamHelper.java:367)
	at com.amazon.redshift.jdbc.RedshiftConnectionImpl.<init>(RedshiftConnectionImpl.java:245)
	at com.amazon.redshift.Driver.makeConnection(Driver.java:489)
	at com.amazon.redshift.Driver.connect(Driver.java:302)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:176)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:195)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:457)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.checkInstanceConnection(PostgreDatabase.java:222)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.<init>(PostgreDatabase.java:115)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.createDatabaseImpl(PostgreDataSource.java:240)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:146)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:97)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:89)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:97)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:108)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:918)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Oct 14 08:36:42.771 FUNCTION  [3 Finalizer] com.amazon.redshift.jdbc.RedshiftConnectionImpl.close:  Enter () 
Oct 14 08:36:42.771 FUNCTION  [3 Finalizer] com.amazon.redshift.jdbc.RedshiftConnectionImpl.close:  Return  

```

**Comment by iggarish** [comment]
What's the full path of your profile credential file? is it ~/.aws/credentials?

**Comment by karlanka** [comment]
> What's the full path of your profile credential file? is it ~/.aws/credentials?

I am on windows, so it is `C:\Users\karlanka\.aws\credentials`.

**Comment by iggarish** [comment]
ok. Can you put your profile in C:\Users\karlanka\.aws\config file and try it out?

**Comment by karlanka** [comment]
The above logs are from having the profile in `C:\Users\karlanka\.aws\config`. I mention `C:\Users\karlanka\.aws\credentials` because this is where I put my `aws_access_key` and `aws_secret_access_key` when I am using a non-sso profile (which works).

**Comment by iggarish** [comment]
Hi Karlanka,

I investigate more and found that AWS SSO profile is not supported.  The driver only support AWS IAM credentials/role in the profile. 

Thanks,
ilesh Garish

**Comment by iggarish** [comment]
AWS SSO is on roadmap but not in immediate plan. Closing the issue for now.
