### ISSUE TITLE
Driver fails on trying to commit a transaction

### ISSUE THREAD

**Issue by juliahayward** [aws/amazon-redshift-jdbc-driver#4]
## Driver version
2.0.0

## Redshift version
`PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.21262`

## Client Operating System
Windows 10

## JAVA/JVM version
```
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+12-b304.10)
OpenJDK 64-Bit Server VM (build 11.0.3+12-b304.10, mixed mode)
```

## Table schema
Starting from empty schema

## Problem description

Using Flyway 7.2, attempt to run trivial migration (eg SELECT 1). With v1.x driver all is well. With v2, it errors with stack:
```
ERROR: Unexpected error
org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: 
Migration V1__first.sql failed
------------------------------
SQL State  : 25P02
Error Code : 0
Message    : ERROR: current transaction is aborted, commands ignored until end of transaction block
Location   : c:\flyway-conf\sql\V1__first.sql (c:\flyway-conf\sql\V1__first.sql)
Line       : 1
Statement  : SELECT version()

	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:432)
	at org.flywaydb.core.internal.command.DbMigrate.access$200(DbMigrate.java:56)
	at org.flywaydb.core.internal.command.DbMigrate$3.call(DbMigrate.java:335)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:332)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:297)
	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:56)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:201)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:198)
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate$1.call(TableLockingExecutionTemplate.java:23)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate.execute(TableLockingExecutionTemplate.java:18)
	at org.flywaydb.core.internal.database.base.Connection.lock(Connection.java:129)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:139)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:198)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:159)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:215)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:164)
	at org.flywaydb.core.Flyway.execute(Flyway.java:538)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:164)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:238)
	at org.flywaydb.commandline.Main.main(Main.java:155)
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: 
Migration V1__first.sql failed
------------------------------
SQL State  : 25P02
Error Code : 0
Message    : ERROR: current transaction is aborted, commands ignored until end of transaction block
Location   : c:\flyway-conf\sql\V1__first.sql (c:\flyway-conf\sql\V1__first.sql)
Line       : 1
Statement  : SELECT version()

	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:273)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:218)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:126)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:82)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.access$000(SqlMigrationExecutor.java:32)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor$1.call(SqlMigrationExecutor.java:70)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor$1.call(SqlMigrationExecutor.java:67)
	at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:28)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:67)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:428)
	... 21 more
Caused by: com.amazon.redshift.util.RedshiftException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at com.amazon.redshift.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2552)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResultsOnThread(QueryExecutorImpl.java:2232)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1860)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1852)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:361)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeInternal(RedshiftStatementImpl.java:509)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.execute(RedshiftStatementImpl.java:430)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeWithFlags(RedshiftStatementImpl.java:371)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeCachedSql(RedshiftStatementImpl.java:357)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeWithFlags(RedshiftStatementImpl.java:334)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.execute(RedshiftStatementImpl.java:324)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:241)
	at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:111)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:206)
	... 29 more
```
The auto-generated script - corresponds to the commands it is trying to run is
```
-- -====================================
-- Flyway Dry Run (2020-11-18 16:02:10)
-- -====================================

SELECT set_config('search_path', '"public",$user, public', false);

-- Executing: validate (with callbacks)
-- ---------------------------------------------------------------------------------------
SELECT set_config('search_path', '"public",$user, public', false);

-- Executing: migrate (with callbacks)
-- ---------------------------------------------------------------------------------------
SELECT set_config('search_path', '"public",$user, public', false);

-- Executing: migrate -> v1 (with callbacks)
-- ---------------------------------------------------------------------------------------

-- Source: c:\flyway-conf\sql\V1__first.sql
-- -----------------------------------------
SELECT version(); // Failure happens here
...
```

The critical piece of code is in `https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/jdbc/TransactionalExecutionTemplate.java:64` - while I haven't isolated it yet (will do if that is the only way to get this fixed), it appears:

```
64:            oldAutocommit = connection.getAutoCommit();
65:            connection.setAutoCommit(false);
66:            T result = callback.call();
67:            connection.commit();
68:            return result;
```

fails; but comment out lines 64/65/67 and it succeeds.

**Comment by juliahayward** [comment]
(This all works with the v1.2.10.1009 driver from Maven Central)

**Comment by iggarish** [comment]
Thanks for reporting problem. Could you please generate JDBC driver log by putting "LogLevel=6;LogPath=/tmp" in the URL? Then run your test and it should generates redshift*.log under /tmp directory in this case.

**Comment by iggarish** [comment]
We have seen this type of error, when some query fail  in a transaction and application is not calling Rollback and keep using same transaction to execute more query. We can confirm it once we have logs.

**Comment by juliahayward** [comment]
[redshift_jdbc.log](https://github.com/aws/amazon-redshift-jdbc-driver/files/5589611/redshift_jdbc.log)
[redshift_jdbc_connection_1.log](https://github.com/aws/amazon-redshift-jdbc-driver/files/5589612/redshift_jdbc_connection_1.log)
[redshift_jdbc_connection_2.log](https://github.com/aws/amazon-redshift-jdbc-driver/files/5589613/redshift_jdbc_connection_2.log)

Log files attached. Many thanks!

**Comment by iggarish** [comment]
Thanks for logs. We will analyze it and get back to you.

**Comment by iggarish** [comment]
As per the log, looks like application is ignoring close statement error and then try to use same connection to execute another statement. Because it was in auto commit off mode, server is expecting rollback() needs to call as part of previous error.
This is the error in the log:
Nov 24 11:43:13.077 ERROR  [1 main] com.amazon.redshift.core.v3.QueryExecutorImpl.closeStatementAndPortal: com.amazon.redshift.util.RedshiftException: ERROR: Query cancelled on user's request
	at com.amazon.redshift.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2552)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processSyncOnClose(QueryExecutorImpl.java:1820)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.closeStatementAndPortal(QueryExecutorImpl.java:1715)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.closeImpl(RedshiftStatementImpl.java:754)
	at com.amazon.redshift.jdbc.RedshiftPreparedStatement.closeImpl(RedshiftPreparedStatement.java:220)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.close(RedshiftStatementImpl.java:741)
	at org.flywaydb.core.internal.jdbc.JdbcUtils.closeStatement(JdbcUtils.java:122)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.execute(JdbcTemplate.java:224)
	at org.flywaydb.core.internal.database.redshift.RedshiftConnection.doChangeCurrentSchemaOrSearchPathTo(RedshiftConnection.java:61)
	at org.flywaydb.core.internal.database.redshift.RedshiftConnection.changeCurrentSchemaTo(RedshiftConnection.java:47)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:421)
	at org.flywaydb.core.internal.command.DbMigrate.access$200(DbMigrate.java:56)
	at org.flywaydb.core.internal.command.DbMigrate$3.call(DbMigrate.java:335)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:332)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:297)
	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:56)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:201)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:198)
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate$1.call(TableLockingExecutionTemplate.java:23)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate.execute(TableLockingExecutionTemplate.java:18)
	at org.flywaydb.core.internal.database.base.Connection.lock(Connection.java:129)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:139)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:198)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:159)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:215)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:164)
	at org.flywaydb.core.Flyway.execute(Flyway.java:538)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:164)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:238)
	at org.flywaydb.commandline.Main.main(Main.java:151)

So please check this line:
org.flywaydb.core.internal.jdbc.JdbcUtils.closeStatement(JdbcUtils.java:122), this should handle the error and should call rollback.

Another way to workaround is: in the URL disable the ring buffer: enableFetchRingBuffer=false.
In this driver by default, ring buffer is enable to fetch rows on a separate thread. If this application close the statement before fetching all rows, cancel call fail.

Please change the application and use the work around. Let us know once you test it.

**Comment by juliahayward** [comment]
Setting `enableFetchRingBuffer=false` seems to be the best for us for the time being, thankyou.

One question - we pass Properties with a nested default values object into connections. https://github.com/aws/amazon-redshift-jdbc-driver/blob/1d0e79c6a9d21e09930808f654fcf8124b8aefe0/src/main/java/com/amazon/redshift/RedshiftProperty.java appears to not search through the nested objects, as `props.put("enableFetchRingBuffer", "false");` works in the top level Properties but gives me:

```
java.lang.NullPointerException
Sleeping until connection valid
```

if in the nested one?

**Comment by iggarish** [comment]
Please try 2.0.0.1 and let us know ring buffer works fine or not.

**Comment by juliahayward** [comment]
It appears to behave the same way as 2.0.0.0?

**Comment by lukaseder** [comment]
I got stuck in that ringbuffer forever after running a random integration test:

![image](https://user-images.githubusercontent.com/734593/120661857-edd9c380-c488-11eb-9c9b-c1cd6f70cc1b.png)

Turning off the feature seemed to help as well...

**Comment by lukaseder** [comment]
For the record, the `RingBufferThread` is in this state:

![image](https://user-images.githubusercontent.com/734593/120662181-35f8e600-c489-11eb-9ce3-0f5c52bdbbcf.png)

**Comment by iggarish** [comment]
We fix similar issue in one of the version. Please use latest version 2.0.0.5. If its happening send us driver logs and if possible repro.

**Comment by juliahayward** [comment]
Still appears to have the same behaviour.

**Comment by iggarish** [comment]
Could you please give me driver log and your test program?
