### ISSUE TITLE
Error retrieving metadata for late binding views which project NULL values in their definition

### ISSUE THREAD

**Issue by iteijeiro** [aws/amazon-redshift-jdbc-driver#45]
## Driver version

2.0.0.4

## Redshift version

PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.35649

## Client Operating System

Windows 10.

## JAVA/JVM version

Java 11 update 8.

## Table schema

`create view redshiftdb.redshift_dev.test_view_null as select NULL AS test1, NULL AS test2 with no schema binding;`

## Problem description

**This affects a customer of Denodo Technologies and Redshift.**

If we have a late binding view defined as our example view `test_view_null`, the JDBC driver will fail to obtain its schema through the standard JDBC method `DatabaseMetaData.getColumns`, with the following error: `ERROR: invalid input syntax for integer: ""`.

If we execute the following SQL command in Redshift, we can see the schema of our example view: 
`select distinct col_name, col_type
from pg_get_late_binding_view_cols()
cols(view_schema name, view_name name, col_name name, col_type varchar, col_num int)
where view_name = 'test_view_null_4'`

This returns:

| col_name                           | col_type                         |
|------------------------------------|----------------------------------|
| test1 | character varying                |
| test2| character varying                |

By analyzing the SQL executed internally by Redshift's JDBC driver, we can see that the driver executes the following fragment when obtaining the schema for a late binding view such as our example view: `regexp_substr('<the_specific_column_type_for_a_character_varying_column>','[0-9]+',7)::integer`

If we use the `col_type` values from our example view and execute the following SQL command in Redshift, we obtain the reported error: `select regexp_substr('character varying','[0-9]+',7)::integer`

This expression expects that the actual column type includes a length attribute (e.g. `character varying(100)`). But, since the column type does not define any length, it fails.

**Comment by iggarish** [comment]
Thanks for reporting the issue. Similar issue has been fix. Can you try latest 2.1.0.4 JDBC driver?

**Comment by iteijeiro** [comment]
This is still failing in 2.1.0.4:

`com.amazon.redshift.util.RedshiftException: ERROR: invalid input syntax for integer: ""
	at com.amazon.redshift.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2601) ~[redshift-jdbc42-2.1.0.4.jar:?]
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResultsOnThread(QueryExecutorImpl.java:2269) ~[redshift-jdbc42-2.1.0.4.jar:?]
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1880) ~[redshift-jdbc42-2.1.0.4.jar:?]
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1872) ~[redshift-jdbc42-2.1.0.4.jar:?]
	at com.amazon.redshift.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368) ~[redshift-jdbc42-2.1.0.4.jar:?]
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeInternal(RedshiftStatementImpl.java:514) ~[redshift-jdbc42-2.1.0.4.jar:?]
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.execute(RedshiftStatementImpl.java:435) ~[redshift-jdbc42-2.1.0.4.jar:?]
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeWithFlags(RedshiftStatementImpl.java:376) ~[redshift-jdbc42-2.1.0.4.jar:?]
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeCachedSql(RedshiftStatementImpl.java:362) ~[redshift-jdbc42-2.1.0.4.jar:?]
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeWithFlags(RedshiftStatementImpl.java:339) ~[redshift-jdbc42-2.1.0.4.jar:?]
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeQuery(RedshiftStatementImpl.java:267) ~[redshift-jdbc42-2.1.0.4.jar:?]
	at com.amazon.redshift.jdbc.RedshiftDatabaseMetaData.getColumns(RedshiftDatabaseMetaData.java:2074) ~[redshift-jdbc42-2.1.0.4.jar:?]`

**Comment by iggarish** [comment]
We are able to reproduce the issue. We will get back to you with solution ASAP.

**Comment by iggarish** [comment]
We fix the issue and it will release as part of next release. Next release will be 2.1.0.5 and plan to release next week.

**Comment by iteijeiro** [comment]
Thanks!

**Comment by iggarish** [comment]
2.1.0.5 released with the fix.
