### ISSUE TITLE
IAM Authentication fails with version 2.1.0.6

### ISSUE THREAD

**Issue by JihongL** [aws/amazon-redshift-jdbc-driver#52]
## Driver version
2.1.0.6

## Redshift version
1.0.37505 

## Client Operating System
Mac OS 12.3.1 (21E258)
DBeaver Version 22.0.4.202205011839

## Problem description
1. Expected behaviour: Connect to Redshift through IAM authentication
2. Actual behaviour: Return errors when attempt authentication
3. Error message/stack trace: com.amazonaws.auth.AWSCredentials
4. Any other details that can be helpful: When using driver version 2.0.0.7, connection was successful.

## JDBC trace logs
2022-05-03 02:14:06.514 - Open [https://repo1.maven.org/maven2/com/amazon/redshift/redshift-jdbc42/2.1.0.6/redshift-jdbc42-2.1.0.6.pom]
2022-05-03 02:14:08.170 - Open [https://repo1.maven.org/maven2/com/amazon/redshift/redshift-jdbc42/2.1.0.6/redshift-jdbc42-2.1.0.6.jar]
2022-05-03 02:14:18.055 - Connect with 'MASKED' (2ED295C0-8E01-460E-8506-CAF256F96EAF-17f2fb12fb8-47e2f3a510cc9e73)
2022-05-03 02:14:18.055 - Configure tunnel
2022-05-03 02:14:18.059 - Connect to tunnel host
2022-05-03 02:14:18.059 - SSH INFO: Connecting to MASKED
2022-05-03 02:14:18.109 - SSH INFO: Connection established
2022-05-03 02:14:18.166 - SSH INFO: Remote version string: SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.3
2022-05-03 02:14:18.166 - SSH INFO: Local version string: SSH-2.0-JSCH-0.1.54
2022-05-03 02:14:18.166 - SSH INFO: CheckCiphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-ctr,arcfour,arcfour128,arcfour256
2022-05-03 02:14:18.167 - SSH INFO: CheckKexes: diffie-hellman-group14-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
2022-05-03 02:14:18.178 - SSH INFO: CheckSignatures: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
2022-05-03 02:14:18.178 - SSH INFO: SSH_MSG_KEXINIT sent
2022-05-03 02:14:18.214 - SSH INFO: SSH_MSG_KEXINIT received
2022-05-03 02:14:18.214 - SSH INFO: kex: server: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
2022-05-03 02:14:18.214 - SSH INFO: kex: server: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
2022-05-03 02:14:18.214 - SSH INFO: kex: server: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
2022-05-03 02:14:18.214 - SSH INFO: kex: server: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
2022-05-03 02:14:18.214 - SSH INFO: kex: server: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
2022-05-03 02:14:18.214 - SSH INFO: kex: server: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
2022-05-03 02:14:18.214 - SSH INFO: kex: server: none,zlib@openssh.com
2022-05-03 02:14:18.214 - SSH INFO: kex: server: none,zlib@openssh.com
2022-05-03 02:14:18.214 - SSH INFO: kex: server: 
2022-05-03 02:14:18.214 - SSH INFO: kex: server: 
2022-05-03 02:14:18.214 - SSH INFO: kex: client: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
2022-05-03 02:14:18.214 - SSH INFO: kex: client: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
2022-05-03 02:14:18.214 - SSH INFO: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
2022-05-03 02:14:18.214 - SSH INFO: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
2022-05-03 02:14:18.214 - SSH INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
2022-05-03 02:14:18.214 - SSH INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
2022-05-03 02:14:18.214 - SSH INFO: kex: client: none
2022-05-03 02:14:18.214 - SSH INFO: kex: client: none
2022-05-03 02:14:18.214 - SSH INFO: kex: client: 
2022-05-03 02:14:18.214 - SSH INFO: kex: client: 
2022-05-03 02:14:18.214 - SSH INFO: kex: server->client aes128-ctr hmac-sha1 none
2022-05-03 02:14:18.214 - SSH INFO: kex: client->server aes128-ctr hmac-sha1 none
2022-05-03 02:14:18.228 - SSH INFO: SSH_MSG_KEX_ECDH_INIT sent
2022-05-03 02:14:18.228 - SSH INFO: expecting SSH_MSG_KEX_ECDH_REPLY
2022-05-03 02:14:18.282 - SSH INFO: ssh_rsa_verify: signature true
2022-05-03 02:14:18.282 - SSH INFO: Host 'MASKED' is known and matches the RSA host key
2022-05-03 02:14:18.282 - SSH INFO: SSH_MSG_NEWKEYS sent
2022-05-03 02:14:18.282 - SSH INFO: SSH_MSG_NEWKEYS received
2022-05-03 02:14:18.282 - SSH INFO: SSH_MSG_SERVICE_REQUEST sent
2022-05-03 02:14:18.327 - SSH INFO: SSH_MSG_SERVICE_ACCEPT received
2022-05-03 02:14:18.381 - SSH INFO: Authentications that can continue: keyboard-interactive
2022-05-03 02:14:18.381 - SSH INFO: Next authentication method: keyboard-interactive
2022-05-03 02:14:19.634 - SSH INFO: Authentication succeeded (keyboard-interactive).
2022-05-03 02:14:19.634 - Set port forwarding :46511 -> MASKED:5439
2022-05-03 02:14:19.636 - Execution context opened (MASKED; Main <MASKED>; 7)
2022-05-03 02:14:19.636 - Initiate connection to PostgreSQL database [MASKED] for Main <MASKED>
2022-05-03 02:14:19.694 - Connection failed (2ED295C0-8E01-460E-8506-CAF256F96EAF-17f2fb12fb8-47e2f3a510cc9e73)
org.jkiss.dbeaver.model.exec.DBCConnectException: Something unusual has occurred to cause the driver to fail. Please report this exception.
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:238)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:467)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.checkInstanceConnection(PostgreDatabase.java:223)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.<init>(PostgreDatabase.java:116)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.createDatabaseImpl(PostgreDataSource.java:250)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:146)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:101)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:93)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:97)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:108)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:983)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:920)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Something unusual has occurred to cause the driver to fail. Please report this exception.
	at com.amazon.redshift.util.RedshiftException.getSQLException(RedshiftException.java:56)
	at com.amazon.redshift.Driver.connect(Driver.java:336)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:187)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:206)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:204)
	... 27 more
Caused by: java.lang.NoClassDefFoundError: com/amazonaws/auth/AWSCredentials
	at com.amazon.redshift.jdbc.RedshiftConnectionImpl.<init>(RedshiftConnectionImpl.java:263)
	at com.amazon.redshift.Driver.makeConnection(Driver.java:499)
	at com.amazon.redshift.Driver.access$100(Driver.java:65)
	at com.amazon.redshift.Driver$ConnectThread.run(Driver.java:408)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.auth.AWSCredentials
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 5 more
2022-05-03 02:14:19.695 - SSH INFO: Disconnecting from MASKED port 22
2022-05-03 02:14:19.695 - SSH INFO: Caught an exception, leaving main loop due to Socket closed
2022-05-03 02:14:19.745 - org.jkiss.dbeaver.model.exec.DBCConnectException: Something unusual has occurred to cause the driver to fail. Please report this exception.
org.jkiss.dbeaver.model.exec.DBCConnectException: Something unusual has occurred to cause the driver to fail. Please report this exception.
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:238)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:467)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.checkInstanceConnection(PostgreDatabase.java:223)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.<init>(PostgreDatabase.java:116)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.createDatabaseImpl(PostgreDataSource.java:250)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.initializeRemoteInstance(PostgreDataSource.java:146)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:101)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:93)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:97)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:108)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:983)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:920)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:80)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Something unusual has occurred to cause the driver to fail. Please report this exception.
	at com.amazon.redshift.util.RedshiftException.getSQLException(RedshiftException.java:56)
	at com.amazon.redshift.Driver.connect(Driver.java:336)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:187)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:206)
	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:204)
	... 27 more
Caused by: java.lang.NoClassDefFoundError: com/amazonaws/auth/AWSCredentials
	at com.amazon.redshift.jdbc.RedshiftConnectionImpl.<init>(RedshiftConnectionImpl.java:263)
	at com.amazon.redshift.Driver.makeConnection(Driver.java:499)
	at com.amazon.redshift.Driver.access$100(Driver.java:65)
	at com.amazon.redshift.Driver$ConnectThread.run(Driver.java:408)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.auth.AWSCredentials
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 5 more
2022-05-03 02:14:19.747 - com.amazonaws.auth.AWSCredentials
java.lang.ClassNotFoundException: com.amazonaws.auth.AWSCredentials
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at com.amazon.redshift.jdbc.RedshiftConnectionImpl.<init>(RedshiftConnectionImpl.java:263)
	at com.amazon.redshift.Driver.makeConnection(Driver.java:499)
	at com.amazon.redshift.Driver.access$100(Driver.java:65)
	at com.amazon.redshift.Driver$ConnectThread.run(Driver.java:408)
	at java.base/java.lang.Thread.run(Unknown Source)

## Reproduction code
https://docs.aws.amazon.com/redshift/latest/mgmt/generating-iam-credentials-configure-jdbc-odbc.html

**Comment by iggarish** [comment]
Please make sure you use the zip file of the driver distribution. Then unzip that and use the driver from the same directory. Basically all dependent jars should be in same directory as the driver jar or you need to provide CLASSPATH for all of them.

**Comment by iggarish** [comment]
I haven't heard anything, so closing it. If it reoccurs, please re-open it with more details and in context with above suggestion works or not.
