### ISSUE TITLE
Acting on a connection can cause spurious rollback/failure of another statement running on another connection in another thread when fetch ring buffer is enabled

### ISSUE THREAD

**Issue by cstenac** [aws/amazon-redshift-jdbc-driver#63]
## Driver version

2.1.0.9

## Redshift version

PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.40182

## Client Operating System

Reproduced on macOS and various Linux

## JAVA/JVM version

1.8.0.131

## Table schema

```create table a_table_with_many_records (i int,s varchar(1000))```

## Problem description

Acting on a connection can cause spurious rollback/failure of another statement running on another connection in another thread.

Conditions:

* connection is in manual commit  mode (`conn.setAutoCommit(false)`)
* enableFetchRingBuffer=true (default)
* You forget to close a ResultSet

Then another connection in another thread that is executing a statement sees this statement aborted:

```
com.amazon.redshift.util.RedshiftException: ERROR: current transaction is aborted, commands ignored until end of transaction block
```

While there is a small misuse of the JDBC API (i.e. closing the statement without closing the ResultSet first), this should not impact another unrelated connection. Disabling fetch ring buffer makes the issue disappear.

Adding a try-with-resource around the ResultSet handling in the attached code makes the issue disappear

## Reproduction code

This code reproduces the issue. However, it should be noted that the issue is highly time-dependent, and won't reproduce in 100% of cases. Sometimes no thread will fail, sometimes just one, sometimes both (corresponding traces attached). The sleep in the code are very empirical, and adequate values for them may depend on your connection latency to Redshift.

```
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

public class RedshiftParallelQueriesFail {
    private static void syso(String s) {
        System.out.println("[" + (System.currentTimeMillis()%60000) + "][tid=" + Thread.currentThread().getId() + "] " + s);
    }

    static class InsertThread extends Thread {
        InsertThread(long index, String url) {
            this.index = index;
            this.url = url;
        }
        private String url;
        private long index;

        public void run() {
            try {
                String query = "insert into output_table_" + index + " select a.* from a_table_with_many_records a inner join a_table_with_many_records b on a.i = b.i";

                syso("Connecting");
                try (Connection conn = DriverManager.getConnection(url)) {
                    syso("connected");

                    conn.setAutoCommit(false);

                    try (Statement st = conn.createStatement()) {
                        st.execute("create table output_table_" + index + "(i int, s varchar(1000))");

                    }
                    syso("output table created");
                    conn.commit();
                    syso("committed");


                    Thread.sleep(10);

                    try (Statement stmt = conn.createStatement()) {
                        String explainQuery = "EXPLAIN " + query;
                        syso("Execution plan query: "+explainQuery);
                        
                        ResultSet rs = stmt.executeQuery(explainQuery);

                        String ep = "";
                        while (rs.next() == true) {
                            ep += rs.getString(1) + "\n";
                        }
                        syso("Explain plan: " + ep);

                        // Misuse here: don't close rs
                    }
                    try (Statement stmt = conn.createStatement()) {
                        String explainQuery = "EXPLAIN " + query;
                        syso("Execution plan query: "+explainQuery);
                        ResultSet rs = stmt.executeQuery(explainQuery);

                        String ep = "";
                        while (rs.next() == true) {
                            ep += rs.getString(1) + "\n";
                        }
                        syso("Explain plan: " + ep);
                        
                        // Misuse here: don't close rs
                    }

                    syso("explain done, starting real execute");

                    try (Statement st = conn.createStatement()) {
                        st.execute("insert into output_table_" + index + " select a.* from a_table_with_many_records a inner join a_table_with_many_records b on a.i = b.i");
                        syso("insert done");
                    }

                    conn.commit();
                    syso("committed");
                }

            } catch (Exception e) {
                syso("Failed");
                e.printStackTrace();
            }
        }
    }

    public static void main(String[] args) throws Exception {
        String url = args[0];

        Class.forName("com.amazon.redshift.jdbc42.Driver");

        try (Connection conn = DriverManager.getConnection(url)) {
            conn.setAutoCommit(false);

            //            try (Statement st = conn.createStatement()) {
            //                st.execute("drop table if exists a_table_with_many_records;");
            //                st.execute("create table a_table_with_many_records (i int,s varchar(1000))");
            //
            //                System.out.println("Table created");
            //
            //                st.execute("insert into a_table_with_many_records values (1, 'my first string is short');");
            //                st.execute("insert into a_table_with_many_records values (2, 'my second string is a bit longer but not so long');");
            //                st.execute("insert into a_table_with_many_records select * from a_table_with_many_records;");
            //                st.execute("insert into a_table_with_many_records select * from a_table_with_many_records;");
            //                st.execute("insert into a_table_with_many_records select * from a_table_with_many_records;");
            //                st.execute("insert into a_table_with_many_records select * from a_table_with_many_records;");
            //                st.execute("insert into a_table_with_many_records select * from a_table_with_many_records;");
            //                st.execute("insert into a_table_with_many_records select * from a_table_with_many_records;");
            //                st.execute("insert into a_table_with_many_records select * from a_table_with_many_records;");
            //                st.execute("insert into a_table_with_many_records select * from a_table_with_many_records;");
            //                st.execute("insert into a_table_with_many_records select * from a_table_with_many_records;");
            //                st.execute("insert into a_table_with_many_records select * from a_table_with_many_records;");
            //                st.execute("insert into a_table_with_many_records select * from a_table_with_many_records;");
            //                st.execute("insert into a_table_with_many_records select * from a_table_with_many_records;");
            //                
            //                st.execute("insert into a_table_with_many_records select * from a_table_with_many_records;");
            //
            //
            //                System.out.println("Table filled");
            //            }
        }
        syso("Starting the threads");


        long beg = System.currentTimeMillis();
        new InsertThread(beg++, url).start();
        Thread.sleep(700);
        new InsertThread(beg++, url).start();
    }
}
```

### Sometimes it works (code output)

```
[16160][tid=1] Starting the threads
[16161][tid=10] Connecting
[16326][tid=10] connected
[16400][tid=10] output table created
[16802][tid=10] committed
[16815][tid=10] Execution plan query: EXPLAIN insert into output_table_1658737876160 select a.* from a_table_with_many_records a inner join a_table_with_many_records b on a.i = b.i
[16867][tid=11] Connecting
[16966][tid=10] Explain plan: XN Hash Join DS_BCAST_INNER  (cost=307.20..2953163941.37 rows=201334937 width=74)
  Hash Cond: ("outer".i = "inner".i)
  ->  XN Seq Scan on a_table_with_many_records a  (cost=0.00..245.76 rows=24576 width=74)
  ->  XN Hash  (cost=245.76..245.76 rows=24576 width=4)
        ->  XN Seq Scan on a_table_with_many_records b  (cost=0.00..245.76 rows=24576 width=4)

[16990][tid=10] Execution plan query: EXPLAIN insert into output_table_1658737876160 select a.* from a_table_with_many_records a inner join a_table_with_many_records b on a.i = b.i
[17033][tid=11] connected
[17040][tid=10] Explain plan: XN Hash Join DS_BCAST_INNER  (cost=307.20..2953163941.37 rows=201334937 width=74)
  Hash Cond: ("outer".i = "inner".i)
  ->  XN Seq Scan on a_table_with_many_records a  (cost=0.00..245.76 rows=24576 width=74)
  ->  XN Hash  (cost=245.76..245.76 rows=24576 width=4)
        ->  XN Seq Scan on a_table_with_many_records b  (cost=0.00..245.76 rows=24576 width=4)

[17063][tid=10] explain done, starting real execute
[17106][tid=11] output table created
[17503][tid=11] committed
[17515][tid=11] Execution plan query: EXPLAIN insert into output_table_1658737876161 select a.* from a_table_with_many_records a inner join a_table_with_many_records b on a.i = b.i
[17700][tid=11] Explain plan: XN Hash Join DS_BCAST_INNER  (cost=307.20..2953163941.37 rows=201334937 width=74)
  Hash Cond: ("outer".i = "inner".i)
  ->  XN Seq Scan on a_table_with_many_records a  (cost=0.00..245.76 rows=24576 width=74)
  ->  XN Hash  (cost=245.76..245.76 rows=24576 width=4)
        ->  XN Seq Scan on a_table_with_many_records b  (cost=0.00..245.76 rows=24576 width=4)

[17722][tid=11] Execution plan query: EXPLAIN insert into output_table_1658737876161 select a.* from a_table_with_many_records a inner join a_table_with_many_records b on a.i = b.i
[17776][tid=11] Explain plan: XN Hash Join DS_BCAST_INNER  (cost=307.20..2953163941.37 rows=201334937 width=74)
  Hash Cond: ("outer".i = "inner".i)
  ->  XN Seq Scan on a_table_with_many_records a  (cost=0.00..245.76 rows=24576 width=74)
  ->  XN Hash  (cost=245.76..245.76 rows=24576 width=4)
        ->  XN Seq Scan on a_table_with_many_records b  (cost=0.00..245.76 rows=24576 width=4)

[17798][tid=11] explain done, starting real execute
```

### Sometimes one of the threads fails (code output)

```
[52536][tid=1] Starting the threads
[52537][tid=10] Connecting
[52725][tid=10] connected
[52809][tid=10] output table created
[53237][tid=11] Connecting
[53326][tid=10] committed
[53340][tid=10] Execution plan query: EXPLAIN insert into output_table_1658737912536 select a.* from a_table_with_many_records a inner join a_table_with_many_records b on a.i = b.i
[53400][tid=11] connected
[53471][tid=11] output table created
[53526][tid=10] Explain plan: XN Hash Join DS_BCAST_INNER  (cost=307.20..2953163941.37 rows=201334937 width=74)
  Hash Cond: ("outer".i = "inner".i)
  ->  XN Seq Scan on a_table_with_many_records a  (cost=0.00..245.76 rows=24576 width=74)
  ->  XN Hash  (cost=245.76..245.76 rows=24576 width=4)
        ->  XN Seq Scan on a_table_with_many_records b  (cost=0.00..245.76 rows=24576 width=4)

[54076][tid=11] committed
[54086][tid=10] Execution plan query: EXPLAIN insert into output_table_1658737912536 select a.* from a_table_with_many_records a inner join a_table_with_many_records b on a.i = b.i
[54086][tid=11] Execution plan query: EXPLAIN insert into output_table_1658737912537 select a.* from a_table_with_many_records a inner join a_table_with_many_records b on a.i = b.i
[54144][tid=10] Failed
com.amazon.redshift.util.RedshiftException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at com.amazon.redshift.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2601)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResultsOnThread(QueryExecutorImpl.java:2269)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1880)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1872)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeInternal(RedshiftStatementImpl.java:514)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.execute(RedshiftStatementImpl.java:435)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeWithFlags(RedshiftStatementImpl.java:376)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeCachedSql(RedshiftStatementImpl.java:362)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeWithFlags(RedshiftStatementImpl.java:339)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeQuery(RedshiftStatementImpl.java:267)
	at RedshiftParallelQueriesFail$InsertThread.run(RedshiftParallelQueriesFail.java:142)
[54236][tid=11] Explain plan: XN Hash Join DS_BCAST_INNER  (cost=307.20..2953163941.37 rows=201334937 width=74)
  Hash Cond: ("outer".i = "inner".i)
  ->  XN Seq Scan on a_table_with_many_records a  (cost=0.00..245.76 rows=24576 width=74)
  ->  XN Hash  (cost=245.76..245.76 rows=24576 width=4)
        ->  XN Seq Scan on a_table_with_many_records b  (cost=0.00..245.76 rows=24576 width=4)

[54259][tid=11] Execution plan query: EXPLAIN insert into output_table_1658737912537 select a.* from a_table_with_many_records a inner join a_table_with_many_records b on a.i = b.i
[54301][tid=11] Explain plan: XN Hash Join DS_BCAST_INNER  (cost=307.20..2953163941.37 rows=201334937 width=74)
  Hash Cond: ("outer".i = "inner".i)
  ->  XN Seq Scan on a_table_with_many_records a  (cost=0.00..245.76 rows=24576 width=74)
  ->  XN Hash  (cost=245.76..245.76 rows=24576 width=4)
        ->  XN Seq Scan on a_table_with_many_records b  (cost=0.00..245.76 rows=24576 width=4)

[54324][tid=11] explain done, starting real execute

``` 

### Sometimes both threads fail (code output + traces)

```
[18260][tid=1] Starting the threads
[18261][tid=10] Connecting
[18430][tid=10] connected
[18521][tid=10] output table created
[18965][tid=11] Connecting
[19147][tid=11] connected
[19217][tid=11] output table created
[20069][tid=10] committed
[20082][tid=10] Execution plan query: EXPLAIN insert into output_table_1658738658261 select a.* from a_table_with_many_records a inner join a_table_with_many_records b on a.i = b.i
[20119][tid=11] committed
[20131][tid=11] Execution plan query: EXPLAIN insert into output_table_1658738658262 select a.* from a_table_with_many_records a inner join a_table_with_many_records b on a.i = b.i
[20333][tid=10] Explain plan: XN Hash Join DS_BCAST_INNER  (cost=307.20..2953163941.37 rows=201334937 width=74)
  Hash Cond: ("outer".i = "inner".i)
  ->  XN Seq Scan on a_table_with_many_records a  (cost=0.00..245.76 rows=24576 width=74)
  ->  XN Hash  (cost=245.76..245.76 rows=24576 width=4)
        ->  XN Seq Scan on a_table_with_many_records b  (cost=0.00..245.76 rows=24576 width=4)

[20358][tid=10] Execution plan query: EXPLAIN insert into output_table_1658738658261 select a.* from a_table_with_many_records a inner join a_table_with_many_records b on a.i = b.i
[20364][tid=11] Explain plan: XN Hash Join DS_BCAST_INNER  (cost=307.20..2953163941.37 rows=201334937 width=74)
  Hash Cond: ("outer".i = "inner".i)
  ->  XN Seq Scan on a_table_with_many_records a  (cost=0.00..245.76 rows=24576 width=74)
  ->  XN Hash  (cost=245.76..245.76 rows=24576 width=4)
        ->  XN Seq Scan on a_table_with_many_records b  (cost=0.00..245.76 rows=24576 width=4)

[20395][tid=10] Explain plan: XN Hash Join DS_BCAST_INNER  (cost=307.20..2953163941.37 rows=201334937 width=74)
  Hash Cond: ("outer".i = "inner".i)
  ->  XN Seq Scan on a_table_with_many_records a  (cost=0.00..245.76 rows=24576 width=74)
  ->  XN Hash  (cost=245.76..245.76 rows=24576 width=4)
        ->  XN Seq Scan on a_table_with_many_records b  (cost=0.00..245.76 rows=24576 width=4)

[21150][tid=11] Execution plan query: EXPLAIN insert into output_table_1658738658262 select a.* from a_table_with_many_records a inner join a_table_with_many_records b on a.i = b.i
[21207][tid=11] Failed
com.amazon.redshift.util.RedshiftException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at com.amazon.redshift.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2607)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResultsOnThread(QueryExecutorImpl.java:2275)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1880)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1872)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeInternal(RedshiftStatementImpl.java:514)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.execute(RedshiftStatementImpl.java:435)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeWithFlags(RedshiftStatementImpl.java:376)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeCachedSql(RedshiftStatementImpl.java:362)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeWithFlags(RedshiftStatementImpl.java:339)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeQuery(RedshiftStatementImpl.java:267)
	at RedshiftParallelQueriesFail$InsertThread.run(RedshiftParallelQueriesFail.java:58)
[21210][tid=10] explain done, starting real execute
[21263][tid=10] Failed
com.amazon.redshift.util.RedshiftException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at com.amazon.redshift.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2607)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResultsOnThread(QueryExecutorImpl.java:2275)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1880)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1872)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeInternal(RedshiftStatementImpl.java:514)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.execute(RedshiftStatementImpl.java:435)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeWithFlags(RedshiftStatementImpl.java:376)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeCachedSql(RedshiftStatementImpl.java:362)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeWithFlags(RedshiftStatementImpl.java:339)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.execute(RedshiftStatementImpl.java:329)
	at RedshiftParallelQueriesFail$InsertThread.run(RedshiftParallelQueriesFail.java:72)
```

/tmp/redshift_jdbc_connection_2.log and /tmp/redshift_jdbc_connection_3.log attached

[redshift_jdbc_connection_2.log](https://github.com/aws/amazon-redshift-jdbc-driver/files/9179527/redshift_jdbc_connection_2.log)
[redshift_jdbc_connection_3.log](https://github.com/aws/amazon-redshift-jdbc-driver/files/9179528/redshift_jdbc_connection_3.log)

**Comment by iggarish** [comment]
Thanks for details. We will look into it and get back to you.

**Comment by bhvkshah** [comment]
We appreciate your patience and your contribution to Redshift JDBC 2.x driver. We have reviewed your issue and have a fix for it. It will be in version 2.1.0.11. Thank you very much!
