### ISSUE TITLE
Driver does not appear to be able to query MixedCase tables

### ISSUE THREAD

**Issue by akuzin1** [aws/amazon-redshift-jdbc-driver#93]
## Driver version

2.1.0.14
## Redshift version

PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.52931
## JAVA/JVM version

Java Version 11
## Table schema

```
MixedCaseTable:
          MixedCasedColumn	int
```
## Problem description

1. Expected behaviour: To be able to query mixed case tables from both the Redshift query editor v2 and JDBC driver.
2. Actual behaviour: Query fails when executing query using JDBC driver.
3. Error message/stack trace:
```
Caused by: com.amazon.redshift.util.RedshiftException: ERROR: relation "public.mixedcasedtable" does not exist
	at com.amazon.redshift.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2601)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResultsOnThread(QueryExecutorImpl.java:2269)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1874)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1866)
	at com.amazon.redshift.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.executeInternal(RedshiftStatementImpl.java:514)
	at com.amazon.redshift.jdbc.RedshiftStatementImpl.execute(RedshiftStatementImpl.java:435)
	at com.amazon.redshift.jdbc.RedshiftPreparedStatement.executeWithFlags(RedshiftPreparedStatement.java:200)
	at com.amazon.redshift.jdbc.RedshiftPreparedStatement.executeQuery(RedshiftPreparedStatement.java:115)
```
5. Any other details that can be helpful:
SQL statement submitted to driver: ```SELECT "MixedCasedColumn" FROM "public"."MixedCasedTable"```

## Reproduction code

```
PreparedStatement preparedStatement = buildSplitSql(connection, readRecordsRequest.getCatalogName(),  readRecordsRequest.getTableName(), readRecordsRequest.getSchema(), readRecordsRequest.getConstraints(), readRecordsRequest.getSplit());
ResultSet resultSet = preparedStatement.executeQuery();

**Comment by bhvkshah** [comment]
Thank you for opening this issue @akuzin1 ! I will investigate and get back to you once I have an update

**Comment by akuzin1** [comment]
Just wanted to check in and ask if any update is available?

**Comment by bhvkshah** [comment]
@akuzin1  To use case-sensitive identifiers (e.g., schema, table, column) in Redshift, you must both set `enable_case_sensitive_identifier` to `true` and also enclose all identifiers in double quotes at all usages. Have you set  `enable_case_sensitive_identifier` to `true`? If not, you can follow documentation [here](https://docs.aws.amazon.com/redshift/latest/dg/r_enable_case_sensitive_identifier.html).

**Comment by akuzin1** [comment]
Yes I have and I verified from the query editor that the query succeeds, does anything need to be configured from driver side?

**Comment by akuzin1** [comment]
Could this be a problem with the driver?

**Comment by akuzin1** [comment]
Hmm ok... I will try again. Thank you.

**Comment by bhvkshah** [comment]
Hi @akuzin1 any updates on this? If you're no longer seeing it we can close this issue.

**Comment by akuzin1** [comment]
Haven't had the opportunity to do additional testing, will prioritize confirming the behavior this upcoming week.

**Comment by bhvkshah** [comment]
@akuzin1 closing this issue as we haven't heard back. If you are still consistently having issues we can dicuss reopening this.
